-- Halley — H2(local) 스키마 (jOOQ 영속화용)
-- live(PostgreSQL) 스키마는 docs/DDL.sql 참조. JSONB → JSON, TEXT → VARCHAR로 치환.

CREATE TABLE IF NOT EXISTS user_group (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_by BIGINT,
    slack_webhook_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id             VARCHAR(50)   NOT NULL,
    nickname             VARCHAR(50)   NOT NULL,
    group_id             BIGINT,
    password_hash        VARCHAR(255)  NOT NULL,
    role                 VARCHAR(20)   NOT NULL DEFAULT 'MEMBER',
    workplace_name       VARCHAR(255),
    workplace_lat        DECIMAL(12, 8),
    workplace_lng        DECIMAL(12, 8),
    must_change_password BOOLEAN       NOT NULL DEFAULT TRUE,
    profile_confirmed    BOOLEAN       NOT NULL DEFAULT FALSE,
    available_budget     BIGINT        NOT NULL DEFAULT 0,
    annual_income        BIGINT       NOT NULL DEFAULT 0,
    existing_loan        BIGINT       NOT NULL DEFAULT 0,
    enabled              BOOLEAN       NOT NULL DEFAULT TRUE,
    disabled_at          TIMESTAMP WITH TIME ZONE,
    disabled_by          BIGINT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_nickname ON users (nickname);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_login_id ON users (login_id);

CREATE TABLE IF NOT EXISTS property (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255),
    dong_ho               VARCHAR(100),
    complex_id            BIGINT,                                        -- 단지 (설계 I266)
    deal_type             VARCHAR(20),
    price_deposit         BIGINT,
    maintenance_fee       INTEGER,
    address_road          VARCHAR(500),
    address_jibun         VARCHAR(500),
    lat                   DECIMAL(12, 8),
    lng                   DECIMAL(12, 8),
    area_supply_m2        DECIMAL(10, 2),
    area_exclusive_m2     DECIMAL(10, 2),
    floor_raw             VARCHAR(50),
    floor_no              INTEGER,
    floor_total           INTEGER,
    floor_band            VARCHAR(10),
    room_bath             VARCHAR(20),
    direction             VARCHAR(50),
    approval_year         INTEGER,
    move_in_type          VARCHAR(20),
    move_in_date          DATE,
    parking_per_household DECIMAL(5, 2),
    total_households      INTEGER,
    heating_type          VARCHAR(50),
    building_count        INTEGER,
    kb_price              BIGINT,
    brokerage_fee         BIGINT,
    brokerage_rate        NUMERIC(4, 2),
    acquisition_tax       BIGINT,
    property_tax          BIGINT,
    comprehensive_tax     VARCHAR(100),
    school_name           VARCHAR(255),
    school_walk_minutes   INTEGER,
    school_source         VARCHAR(20),
    pnu                   VARCHAR(19),
    official_price        BIGINT,
    official_price_year   INTEGER,
    source_type           VARCHAR(20),
    source_url            VARCHAR(1000),
    naver_article_no      VARCHAR(50),
    raw_paste_text        VARCHAR(1000000),
    parser_version        VARCHAR(50),
    parse_confidence      JSON,
    is_draft              BOOLEAN       NOT NULL DEFAULT FALSE,
    listing_status        VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    active                BOOLEAN       NOT NULL DEFAULT TRUE,
    last_checked_at       TIMESTAMP WITH TIME ZONE,
    check_fail_streak     INTEGER       NOT NULL DEFAULT 0,
    sold_detected_at      TIMESTAMP WITH TIME ZONE,
    group_id        BIGINT        NOT NULL,
    created_by_nickname VARCHAR(50),
    created_by            BIGINT,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_name     VARCHAR(255),
    agent_name      VARCHAR(100),
    phone           VARCHAR(30),
    mobile          VARCHAR(30),
    registration_no VARCHAR(100),
    address         VARCHAR(500),
    lat             DECIMAL(12, 8),
    lng             DECIMAL(12, 8)
);

CREATE TABLE IF NOT EXISTS property_agent (
    property_id BIGINT  NOT NULL,
    agent_id    BIGINT  NOT NULL,
    is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (property_id, agent_id)
);

CREATE TABLE IF NOT EXISTS property_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT       NOT NULL,
    image_type   VARCHAR(20)  NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    sort_order   INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS criterion (
    code         VARCHAR(50)  PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    scoring_type VARCHAR(20)  NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS criterion_weight (
    criterion_code VARCHAR(50)   PRIMARY KEY,
    priority_rank  INTEGER       NOT NULL,
    weight         DECIMAL(6, 2) NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_criterion_weight_rank ON criterion_weight (priority_rank);

CREATE TABLE IF NOT EXISTS property_score (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id     BIGINT       NOT NULL,
    criterion_code  VARCHAR(50)  NOT NULL,
    auto_score      DECIMAL(6, 2),
    manual_score    DECIMAL(6, 2),
    effective_score DECIMAL(6, 2),
    score_source    VARCHAR(20),
    fallback_reason VARCHAR(255),
    explanation     VARCHAR(500),
    computed_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_property_score UNIQUE (property_id, criterion_code)
);

CREATE TABLE IF NOT EXISTS user_criterion_score (
    property_id    BIGINT      NOT NULL,
    user_id        BIGINT      NOT NULL,
    criterion_code VARCHAR(50) NOT NULL,
    score          INTEGER     NOT NULL,
    PRIMARY KEY (property_id, user_id, criterion_code)
);

CREATE TABLE IF NOT EXISTS commute_result (
    property_id    BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    total_minutes  INTEGER,
    transfer_count INTEGER,
    walk_minutes   INTEGER,
    path_summary   JSON,
    fetched_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (property_id, user_id)
);

CREATE TABLE IF NOT EXISTS property_opinion (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT        NOT NULL,
    user_id      BIGINT        NOT NULL,
    opinion_type VARCHAR(20)   NOT NULL,
    content      VARCHAR(1000) NOT NULL,
    sort_order   INTEGER       NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS listing_check_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT       NOT NULL,
    checked_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    http_status INTEGER,
    verdict     VARCHAR(20),
    evidence    VARCHAR(1000),
    elapsed_ms  INTEGER,
    notified    BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS system_config (
    config_key   VARCHAR(100)  PRIMARY KEY,
    config_value VARCHAR(1000),
    value_type   VARCHAR(20)   NOT NULL DEFAULT 'STRING',
    category     VARCHAR(20),
    description  VARCHAR(500),
    masked       BOOLEAN       NOT NULL DEFAULT FALSE,
    updated_by   BIGINT,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    VARCHAR(50)  NOT NULL,
    property_id   BIGINT,
    channel       VARCHAR(20),
    status        VARCHAR(20)  NOT NULL DEFAULT 'RETRYING',
    retry_count   INTEGER      NOT NULL DEFAULT 0,
    error_message VARCHAR(1000),
    payload       JSON,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at       TIMESTAMP WITH TIME ZONE
);

-- 단지 (설계 I266). 매물이 여기에 딸린다 — 단지 1 : 매물 N.
-- 그룹으로 가르지 않는다. 아파트 단지는 공개 정보이고, 격리는 property.group_id 가 한다
CREATE TABLE IF NOT EXISTS complex (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_key     VARCHAR(300) NOT NULL UNIQUE,
    name          VARCHAR(200) NOT NULL,
    address_jibun VARCHAR(300),
    lat           NUMERIC(10, 7),
    lng           NUMERIC(10, 7),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 국토부 실거래는 매물이 아니라 <단지 + 평형>에 붙는다 (설계 I266).
-- 같은 단지 같은 평형이면 매물이 몇이든 국토부를 한 번만 부른다
CREATE TABLE IF NOT EXISTS reference_transaction (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complex_id    BIGINT NOT NULL,
    deal_type     VARCHAR(20),
    contract_date DATE,
    price         BIGINT,
    area_m2       NUMERIC(10, 2),
    floor_no      INTEGER,
    source        VARCHAR(30),
    cached_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_reference_transaction_complex
    ON reference_transaction (complex_id, area_m2);

CREATE TABLE IF NOT EXISTS loan_estimate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id     BIGINT NOT NULL,
    product_type    VARCHAR(20),
    ltv_rate        DECIMAL(6, 4),
    ltv_limit       BIGINT,
    dsr_limit       BIGINT,
    final_limit     BIGINT,
    required_cash   BIGINT,
    acquisition_tax BIGINT,
    assumptions     JSON,
    computed_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS property_comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id     BIGINT        NOT NULL,
    author_nickname VARCHAR(50),
    content     VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_property_comment UNIQUE (property_id, user_id)
);

CREATE TABLE IF NOT EXISTS comparative_analysis (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    rank_no        INTEGER,
    score          NUMERIC(6, 2),
    reason         VARCHAR(2000),
    model          VARCHAR(100),
    batch_hash     VARCHAR(64),
    property_count INTEGER,
    computed_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_comparative_analysis UNIQUE (property_id)
);

CREATE TABLE IF NOT EXISTS llm_recommendation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    score        NUMERIC(6, 2),
    reason       VARCHAR(2000),
    model        VARCHAR(100),
    prompt_hash  VARCHAR(64),
    workplace_count INTEGER    NOT NULL DEFAULT 0,
    computed_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_llm_recommendation UNIQUE (property_id)
);

-- 임장 방문 기록 (설계 I197) — 계획이 아니라 매물에 붙는다
CREATE TABLE IF NOT EXISTS property_visit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    visited_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_property_visit UNIQUE (property_id, user_id)
);

CREATE TABLE IF NOT EXISTS regulation_param (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile     VARCHAR(50)   NOT NULL,
    param_key   VARCHAR(50)   NOT NULL,
    param_value VARCHAR(1000) NOT NULL,
    value_type  VARCHAR(20)   NOT NULL DEFAULT 'STRING',
    description VARCHAR(500),
    updated_by  BIGINT,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_regulation_param UNIQUE (profile, param_key)
);

CREATE TABLE IF NOT EXISTS land_use (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT       NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    zone_code   VARCHAR(20),
    zone_name   VARCHAR(200) NOT NULL,
    conflict    VARCHAR(10)  NOT NULL,
    pnu         VARCHAR(19),
    fetched_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS regulated_area (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_prefix   VARCHAR(10) NOT NULL,
    zone          VARCHAR(30) NOT NULL,
    area_name     VARCHAR(200),
    designated_on DATE,
    released_on   DATE,
    note          VARCHAR(500),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_regulated_area UNIQUE (code_prefix, zone, designated_on)
);

CREATE TABLE IF NOT EXISTS legal_dong_code (
    code       VARCHAR(10) PRIMARY KEY,
    sido       VARCHAR(100),
    sigungu    VARCHAR(100),
    dong_name  VARCHAR(100),
    ri_name    VARCHAR(100),
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS regulation_notice (
    zone          VARCHAR(30) PRIMARY KEY,
    notice_no     VARCHAR(50),
    announced_on  DATE,
    seed_status   VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    area_count    INT NOT NULL DEFAULT 0,
    message       VARCHAR(500),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_invite (
    code       VARCHAR(8) PRIMARY KEY,
    group_id   BIGINT NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_debt (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    debt_type  VARCHAR(30)  NOT NULL,
    amount     BIGINT       NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_debt UNIQUE (user_id, debt_type)
);

CREATE TABLE IF NOT EXISTS monthly_trade_cache (
    lawd_cd     VARCHAR(5)  NOT NULL,
    deal_ym     VARCHAR(6)  NOT NULL,
    deal_type   VARCHAR(20) NOT NULL DEFAULT 'TRADE',
    payload     JSON,
    trade_count INT         NOT NULL DEFAULT 0,
    fetched_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (lawd_cd, deal_ym, deal_type)
);

CREATE TABLE IF NOT EXISTS price_forecast (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT       NOT NULL,
    direction      VARCHAR(20)  NOT NULL,
    -- LLM 이 스스로 낸 결론 (설계 I249). direction 은 규칙까지 거친 최종 결론이라
    -- 둘이 다를 수 있다 — 누가 무엇을 말했는지 남겨야 '유력'을 가릴 수 있다
    llm_direction  VARCHAR(20),
    code_direction VARCHAR(20),
    confidence     VARCHAR(20)  NOT NULL,
    horizon_months INT          NOT NULL,
    factors        JSON,
    caveats        JSON,
    model          VARCHAR(100),
    prompt_hash    VARCHAR(64),
    computed_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_price_forecast_property ON price_forecast (property_id);

CREATE TABLE IF NOT EXISTS price_forecast_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT       NOT NULL,
    direction      VARCHAR(20)  NOT NULL,
    -- LLM 이 스스로 낸 결론 (설계 I249). direction 은 규칙까지 거친 최종 결론이라
    -- 둘이 다를 수 있다 — 누가 무엇을 말했는지 남겨야 '유력'을 가릴 수 있다
    llm_direction  VARCHAR(20),
    code_direction VARCHAR(20),
    confidence     VARCHAR(20)  NOT NULL,
    horizon_months INT          NOT NULL,
    factors        JSON,
    caveats        JSON,
    model          VARCHAR(100),
    prompt_hash    VARCHAR(64),
    computed_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_price_forecast_history_property
    ON price_forecast_history (property_id, computed_at DESC);

-- 신혼 생활 시작 예산 계획 (설계 I294). JSONB 대신 H2 호환 SQL을 사용한다.
CREATE TABLE IF NOT EXISTS household_budget_item_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seed_key VARCHAR(50) NOT NULL UNIQUE,
    category VARCHAR(30) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    recommended BOOLEAN NOT NULL DEFAULT FALSE,
    default_budget_amount_won BIGINT NOT NULL DEFAULT 0,
    candidate_name VARCHAR(500), candidate_url VARCHAR(2000),
    alternative_name VARCHAR(500), alternative_url VARCHAR(2000),
    note VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_household_budget_item_catalog_amount CHECK (default_budget_amount_won >= 0)
);

CREATE TABLE IF NOT EXISTS household_budget_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    created_by BIGINT,
    plan_name VARCHAR(100) NOT NULL,
    scenario VARCHAR(20) NOT NULL DEFAULT 'RECOMMENDED',
    selected_property_id BIGINT,
    housing_type VARCHAR(20) NOT NULL DEFAULT 'SALE',
    region VARCHAR(255), house_name VARCHAR(255), purchase_price BIGINT NOT NULL DEFAULT 0,
    exclusive_area_m2 NUMERIC(10, 2), contract_cash BIGINT NOT NULL DEFAULT 0,
    balance_cash BIGINT NOT NULL DEFAULT 0, acquisition_tax BIGINT NOT NULL DEFAULT 0,
    brokerage_fee BIGINT NOT NULL DEFAULT 0, registration_fee BIGINT NOT NULL DEFAULT 0,
    moving_cost BIGINT NOT NULL DEFAULT 0, cleaning_cost BIGINT NOT NULL DEFAULT 0,
    acquisition_tax_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL', brokerage_fee_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    registration_fee_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL', moving_cost_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    cleaning_cost_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    other_initial_cost BIGINT NOT NULL DEFAULT 0, parent_support BIGINT NOT NULL DEFAULT 0,
    other_funds BIGINT NOT NULL DEFAULT 0, monthly_management_fee BIGINT NOT NULL DEFAULT 0,
    monthly_other_housing_cost BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE household_budget_plan ADD COLUMN IF NOT EXISTS acquisition_tax_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE household_budget_plan ADD COLUMN IF NOT EXISTS brokerage_fee_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE household_budget_plan ADD COLUMN IF NOT EXISTS registration_fee_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE household_budget_plan ADD COLUMN IF NOT EXISTS moving_cost_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE household_budget_plan ADD COLUMN IF NOT EXISTS cleaning_cost_source VARCHAR(20) NOT NULL DEFAULT 'MANUAL';
CREATE INDEX IF NOT EXISTS ix_household_budget_plan_group ON household_budget_plan (group_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS household_budget_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL, user_id BIGINT NOT NULL,
    asset_type VARCHAR(30) NOT NULL, asset_name VARCHAR(255) NOT NULL,
    estimated_value BIGINT NOT NULL DEFAULT 0, excluded BOOLEAN NOT NULL DEFAULT FALSE,
    investable_amount BIGINT NOT NULL DEFAULT 0, source_type VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
    note VARCHAR(1000), created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_household_budget_asset_amounts CHECK (estimated_value >= 0 AND investable_amount >= 0 AND investable_amount <= estimated_value)
);
CREATE INDEX IF NOT EXISTS ix_household_budget_asset_plan ON household_budget_asset (plan_id, user_id);

CREATE TABLE IF NOT EXISTS household_budget_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL, seed_key VARCHAR(50), category VARCHAR(30) NOT NULL,
    item_name VARCHAR(255) NOT NULL, required BOOLEAN NOT NULL DEFAULT FALSE,
    recommended BOOLEAN NOT NULL DEFAULT FALSE, selected BOOLEAN NOT NULL DEFAULT FALSE,
    owned BOOLEAN NOT NULL DEFAULT FALSE, budget_amount_won BIGINT NOT NULL DEFAULT 0,
    candidate_name VARCHAR(500), candidate_url VARCHAR(2000), candidate_price_won BIGINT,
    alternative_name VARCHAR(500), alternative_url VARCHAR(2000), alternative_price_won BIGINT,
    candidate_fetch_status VARCHAR(30) NOT NULL DEFAULT 'NOT_FETCHED',
    alternative_fetch_status VARCHAR(30) NOT NULL DEFAULT 'NOT_FETCHED', note VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_household_budget_item_plan_seed UNIQUE (plan_id, seed_key),
    CONSTRAINT ck_household_budget_item_amounts CHECK (budget_amount_won >= 0 AND (candidate_price_won IS NULL OR candidate_price_won >= 0) AND (alternative_price_won IS NULL OR alternative_price_won >= 0))
);
CREATE INDEX IF NOT EXISTS ix_household_budget_item_plan ON household_budget_item (plan_id, category);

CREATE TABLE IF NOT EXISTS household_budget_financing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL, loan_amount BIGINT NOT NULL DEFAULT 0,
    loan_ratio NUMERIC(7, 4), interest_rate NUMERIC(7, 4) NOT NULL DEFAULT 0,
    term_months INTEGER NOT NULL DEFAULT 360, repayment_type VARCHAR(30) NOT NULL DEFAULT 'AMORTIZED',
    monthly_payment BIGINT NOT NULL DEFAULT 0, is_estimate BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_household_budget_financing_plan UNIQUE (plan_id),
    CONSTRAINT ck_household_budget_financing_amounts CHECK (loan_amount >= 0 AND interest_rate >= 0 AND term_months > 0 AND monthly_payment >= 0)
);

CREATE TABLE IF NOT EXISTS open_banking_connection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, provider VARCHAR(30) NOT NULL DEFAULT 'KFTC_OPEN_BANKING',
    encrypted_access_token VARCHAR(4096) NOT NULL, encrypted_refresh_token VARCHAR(4096),
    token_expires_at TIMESTAMP WITH TIME ZONE NOT NULL, consented_at TIMESTAMP WITH TIME ZONE NOT NULL,
    disconnected_at TIMESTAMP WITH TIME ZONE, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_open_banking_connection_user_provider UNIQUE (user_id, provider)
);

CREATE TABLE IF NOT EXISTS open_banking_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL, fintech_use_num_hash VARCHAR(64) NOT NULL,
    encrypted_fintech_use_num VARCHAR(1024) NOT NULL, fintech_use_num_masked VARCHAR(32) NOT NULL,
    bank_code VARCHAR(10), bank_name VARCHAR(100), product_name VARCHAR(255), account_type VARCHAR(50),
    last_balance_amt BIGINT, last_available_amt BIGINT, last_synced_at TIMESTAMP WITH TIME ZONE,
    linked_budget_asset_id BIGINT, active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ux_open_banking_account_connection_hash UNIQUE (connection_id, fintech_use_num_hash),
    CONSTRAINT ck_open_banking_account_amounts CHECK ((last_balance_amt IS NULL OR last_balance_amt >= 0) AND (last_available_amt IS NULL OR last_available_amt >= 0))
);
CREATE INDEX IF NOT EXISTS ix_open_banking_account_connection ON open_banking_account (connection_id, active);

CREATE TABLE IF NOT EXISTS open_banking_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id BIGINT NOT NULL, requested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE, status VARCHAR(30) NOT NULL, failure_code VARCHAR(100),
    account_count INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_open_banking_sync_log_count CHECK (account_count >= 0)
);
CREATE INDEX IF NOT EXISTS ix_open_banking_sync_log_connection ON open_banking_sync_log (connection_id, requested_at DESC);
