-- Halley — H2(local) 스키마 (jOOQ 영속화용)
-- live(PostgreSQL) 스키마는 docs/DDL.sql 참조. JSONB → JSON, TEXT → VARCHAR로 치환.

CREATE TABLE IF NOT EXISTS users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id             VARCHAR(50)   NOT NULL,
    nickname             VARCHAR(50)   NOT NULL,
    email                VARCHAR(255),
    password_hash        VARCHAR(255)  NOT NULL,
    role                 VARCHAR(20)   NOT NULL DEFAULT 'MEMBER',
    workplace_name       VARCHAR(255),
    workplace_lat        DECIMAL(12, 8),
    workplace_lng        DECIMAL(12, 8),
    must_change_password BOOLEAN       NOT NULL DEFAULT TRUE,
    available_budget     BIGINT        NOT NULL DEFAULT 0,
    annual_income        BIGINT       NOT NULL DEFAULT 0,
    existing_loan        BIGINT       NOT NULL DEFAULT 0,
    enabled              BOOLEAN       NOT NULL DEFAULT TRUE,
    disabled_at          TIMESTAMP WITH TIME ZONE,
    disabled_by          BIGINT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_nickname ON users (nickname);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email    ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_login_id ON users (login_id);

CREATE TABLE IF NOT EXISTS property (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255),
    dong_ho               VARCHAR(100),
    deal_type             VARCHAR(20),
    price_deposit         BIGINT,
    price_monthly         BIGINT,
    maintenance_fee       INTEGER,
    address_road          VARCHAR(500),
    address_jibun         VARCHAR(500),
    lat                   DECIMAL(12, 8),
    lng                   DECIMAL(12, 8),
    area_supply_m2        DECIMAL(10, 2),
    area_exclusive_m2     DECIMAL(10, 2),
    floor_raw             VARCHAR(50),
    floor_no              INTEGER,
    floor_total           INTEGER,
    floor_band            VARCHAR(10),
    room_bath             VARCHAR(20),
    direction             VARCHAR(50),
    approval_year         INTEGER,
    move_in_type          VARCHAR(20),
    move_in_date          DATE,
    parking_per_household DECIMAL(5, 2),
    total_households      INTEGER,
    heating_type          VARCHAR(50),
    building_count        INTEGER,
    kb_price              BIGINT,
    brokerage_fee         BIGINT,
    brokerage_rate        NUMERIC(4, 2),
    acquisition_tax       BIGINT,
    property_tax          BIGINT,
    comprehensive_tax     VARCHAR(100),
    school_name           VARCHAR(255),
    school_walk_minutes   INTEGER,
    school_source         VARCHAR(20),
    pnu                   VARCHAR(19),
    official_price        BIGINT,
    official_price_year   INTEGER,
    source_type           VARCHAR(20),
    source_url            VARCHAR(1000),
    naver_article_no      VARCHAR(50),
    raw_paste_text        VARCHAR(1000000),
    parser_version        VARCHAR(50),
    parse_confidence      JSON,
    is_draft              BOOLEAN       NOT NULL DEFAULT FALSE,
    listing_status        VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    active                BOOLEAN       NOT NULL DEFAULT TRUE,
    last_checked_at       TIMESTAMP WITH TIME ZONE,
    check_fail_streak     INTEGER       NOT NULL DEFAULT 0,
    sold_detected_at      TIMESTAMP WITH TIME ZONE,
    created_by            BIGINT,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS agent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_name     VARCHAR(255),
    agent_name      VARCHAR(100),
    phone           VARCHAR(30),
    mobile          VARCHAR(30),
    registration_no VARCHAR(100),
    address         VARCHAR(500),
    lat             DECIMAL(12, 8),
    lng             DECIMAL(12, 8)
);

CREATE TABLE IF NOT EXISTS property_agent (
    property_id BIGINT  NOT NULL,
    agent_id    BIGINT  NOT NULL,
    is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (property_id, agent_id)
);

CREATE TABLE IF NOT EXISTS property_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT       NOT NULL,
    image_type   VARCHAR(20)  NOT NULL,
    storage_path VARCHAR(500) NOT NULL,
    sort_order   INTEGER      NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS criterion (
    code         VARCHAR(50)  PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    scoring_type VARCHAR(20)  NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS criterion_weight (
    criterion_code VARCHAR(50)   PRIMARY KEY,
    priority_rank  INTEGER       NOT NULL,
    weight         DECIMAL(6, 2) NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_criterion_weight_rank ON criterion_weight (priority_rank);

CREATE TABLE IF NOT EXISTS property_score (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id     BIGINT       NOT NULL,
    criterion_code  VARCHAR(50)  NOT NULL,
    auto_score      DECIMAL(6, 2),
    manual_score    DECIMAL(6, 2),
    effective_score DECIMAL(6, 2),
    score_source    VARCHAR(20),
    fallback_reason VARCHAR(255),
    explanation     VARCHAR(500),
    computed_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_property_score UNIQUE (property_id, criterion_code)
);

CREATE TABLE IF NOT EXISTS user_criterion_score (
    property_id    BIGINT      NOT NULL,
    user_id        BIGINT      NOT NULL,
    criterion_code VARCHAR(50) NOT NULL,
    score          INTEGER     NOT NULL,
    PRIMARY KEY (property_id, user_id, criterion_code)
);

CREATE TABLE IF NOT EXISTS commute_result (
    property_id    BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    total_minutes  INTEGER,
    transfer_count INTEGER,
    walk_minutes   INTEGER,
    path_summary   JSON,
    fetched_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (property_id, user_id)
);

CREATE TABLE IF NOT EXISTS property_opinion (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT        NOT NULL,
    user_id      BIGINT        NOT NULL,
    opinion_type VARCHAR(20)   NOT NULL,
    content      VARCHAR(1000) NOT NULL,
    sort_order   INTEGER       NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS listing_check_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT       NOT NULL,
    checked_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    http_status INTEGER,
    verdict     VARCHAR(20),
    evidence    VARCHAR(1000),
    elapsed_ms  INTEGER,
    notified    BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS system_config (
    config_key   VARCHAR(100)  PRIMARY KEY,
    config_value VARCHAR(1000),
    value_type   VARCHAR(20)   NOT NULL DEFAULT 'STRING',
    category     VARCHAR(20),
    description  VARCHAR(500),
    masked       BOOLEAN       NOT NULL DEFAULT FALSE,
    updated_by   BIGINT,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    VARCHAR(50)  NOT NULL,
    property_id   BIGINT,
    channel       VARCHAR(20),
    status        VARCHAR(20)  NOT NULL DEFAULT 'RETRYING',
    retry_count   INTEGER      NOT NULL DEFAULT 0,
    error_message VARCHAR(1000),
    payload       JSON,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at       TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS reference_transaction (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id   BIGINT NOT NULL,
    deal_type     VARCHAR(20),
    contract_date DATE,
    price         BIGINT,
    floor_no      INTEGER,
    source        VARCHAR(30),
    cached_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS loan_estimate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id     BIGINT NOT NULL,
    product_type    VARCHAR(20),
    ltv_rate        DECIMAL(6, 4),
    ltv_limit       BIGINT,
    dsr_limit       BIGINT,
    final_limit     BIGINT,
    required_cash   BIGINT,
    acquisition_tax BIGINT,
    assumptions     JSON,
    computed_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS property_comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id     BIGINT        NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    content     VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_property_comment UNIQUE (property_id, user_id)
);

CREATE TABLE IF NOT EXISTS comparative_analysis (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    rank_no        INTEGER,
    score          NUMERIC(6, 2),
    reason         VARCHAR(2000),
    model          VARCHAR(100),
    batch_hash     VARCHAR(64),
    property_count INTEGER,
    computed_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_comparative_analysis UNIQUE (property_id)
);

CREATE TABLE IF NOT EXISTS llm_recommendation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    score        NUMERIC(6, 2),
    reason       VARCHAR(2000),
    model        VARCHAR(100),
    prompt_hash  VARCHAR(64),
    workplace_count INTEGER    NOT NULL DEFAULT 0,
    computed_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_llm_recommendation UNIQUE (property_id)
);

CREATE TABLE IF NOT EXISTS property_visit_plan (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_date           DATE,
    created_by           BIGINT NOT NULL,
    start_address        VARCHAR(500),
    start_lat            DECIMAL(12, 8),
    start_lng            DECIMAL(12, 8),
    travel_mode          VARCHAR(20),
    window_start         TIME,
    window_end           TIME,
    stay_minutes_default INTEGER NOT NULL DEFAULT 25,
    status               VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    computed_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visit_plan_stop (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id                  BIGINT  NOT NULL,
    property_id              BIGINT  NOT NULL,
    stop_order               INTEGER NOT NULL,
    estimated_arrival        TIME,
    estimated_departure      TIME,
    travel_minutes_from_prev INTEGER,
    travel_mode_segment      VARCHAR(20),
    visited                  BOOLEAN NOT NULL DEFAULT FALSE,
    visited_at               TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_visit_plan_stop_order UNIQUE (plan_id, stop_order)
);

CREATE TABLE IF NOT EXISTS regulation_param (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile     VARCHAR(50)   NOT NULL,
    param_key   VARCHAR(50)   NOT NULL,
    param_value VARCHAR(1000) NOT NULL,
    value_type  VARCHAR(20)   NOT NULL DEFAULT 'STRING',
    description VARCHAR(500),
    updated_by  BIGINT,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_regulation_param UNIQUE (profile, param_key)
);

CREATE TABLE IF NOT EXISTS legal_dong_code (
    code       VARCHAR(10) PRIMARY KEY,
    sido       VARCHAR(100),
    sigungu    VARCHAR(100),
    dong_name  VARCHAR(100),
    ri_name    VARCHAR(100),
    is_active  BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
