-- =============================================================================
-- Halley — 부동산 매물 비교·평가 웹앱 DB 스키마 (PostgreSQL)
--
-- 대상 : live = PostgreSQL, local = H2 (PostgreSQL 호환 모드)
--        JSONB 등 PostgreSQL 전용 기능은 outbound adapter 뒤에 격리한다 (설계서 2.3).
-- 명명 : snake_case, PK는 BIGINT IDENTITY (자연키 테이블 제외).
-- 근거 : docs/DESIGN.md 4장(ERD), 10.2(임장), 3.4/16-I35(규제 파라미터), 5.5(법정동코드)
--
-- 운영 DB가 이 파일의 어느 시점에 멈춰 있어 기동하지 못한다면
-- (`relation "..." does not exist`), 이 파일을 다시 돌리지 말고
-- **docs/DDL-repair.sql** 을 쓴다. 전부 IF NOT EXISTS 라 현재 상태와 무관하게
-- 안전하고, 몇 번을 돌려도 같은 결과다.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. users — 사용자 (Admin이 생성, 회원가입 없음)
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id             VARCHAR(50)  NOT NULL,                        -- 로그인 ID (설계 I51)
    nickname             VARCHAR(50)  NOT NULL,
    email                VARCHAR(255),                                  -- 연락처. 최초 설정에서 강제 입력
    password_hash        VARCHAR(255) NOT NULL,
    role                 VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',        -- ADMIN | MEMBER
    workplace_name       VARCHAR(255),
    workplace_lat        NUMERIC(12, 8),
    workplace_lng        NUMERIC(12, 8),
    must_change_password BOOLEAN      NOT NULL DEFAULT TRUE,
    available_budget     BIGINT       NOT NULL DEFAULT 0,               -- 보유 현금(원) — 예산상한 합산·자기자본 (I55)
    annual_income        BIGINT       NOT NULL DEFAULT 0,               -- 연소득(원) — DSR 산정 (설계 I55)
    existing_loan        BIGINT       NOT NULL DEFAULT 0,               -- 기존 대출 잔액(원) — DSR 차감
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    disabled_at          TIMESTAMPTZ,
    disabled_by          BIGINT       REFERENCES users (id),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_users_nickname ON users (nickname);
CREATE UNIQUE INDEX ux_users_email    ON users (email);
CREATE UNIQUE INDEX ux_users_login_id ON users (login_id);
CREATE INDEX        ix_users_role     ON users (role);

-- ---------------------------------------------------------------------------
-- 2. property — 매물
-- ---------------------------------------------------------------------------
CREATE TABLE property (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255),                                  -- 단지명
    dong_ho               VARCHAR(100),                                  -- 동/호
    deal_type             VARCHAR(20),                                   -- SALE | JEONSE | MONTHLY
    price_deposit         BIGINT,                                        -- 매매가 or 보증금(원)
    maintenance_fee       INTEGER,
    address_road          VARCHAR(500),
    address_jibun         VARCHAR(500),
    lat                   NUMERIC(12, 8),
    lng                   NUMERIC(12, 8),
    area_supply_m2        NUMERIC(10, 2),                                -- 공급면적(㎡)
    area_exclusive_m2     NUMERIC(10, 2),                                -- 전용면적(㎡)
    floor_raw             VARCHAR(50),                                   -- '7' or '고/중/저'
    floor_no              INTEGER,
    floor_total           INTEGER,
    floor_band            VARCHAR(10),                                   -- HIGH | MID | LOW
    room_bath             VARCHAR(20),                                   -- '3/2'
    direction             VARCHAR(50),
    approval_year         INTEGER,                                       -- 사용승인연도
    move_in_type          VARCHAR(20),                                   -- IMMEDIATE | NEGOTIABLE | DATE
    move_in_date          DATE,
    parking_per_household NUMERIC(5, 2),                                 -- 세대당 주차대수
    total_households      INTEGER,
    heating_type          VARCHAR(50),
    building_count        INTEGER,                                       -- 단지 동수 — 수기 입력
    kb_price              BIGINT,                                        -- KB시세 — 대출 산정 기준
    brokerage_fee         BIGINT,                                        -- 중개보수 상한액(원) — 설계 I53
    brokerage_rate        NUMERIC(4, 2),                                 -- 중개보수 상한 요율(%)
    acquisition_tax       BIGINT,                                        -- 취득세 합계(원)
    property_tax          BIGINT,                                        -- 재산세 합계(원)
    comprehensive_tax     VARCHAR(100),                                  -- 종합부동산세 — '과세대상 아님' 등 문구 그대로
    school_name           VARCHAR(255),                                  -- 배정 초등학교
    school_walk_minutes   INTEGER,                                       -- 초등학교 도보 분
    school_source         VARCHAR(20),                                   -- PASTE | KAKAO (파싱 실패 시 비동기 보정)
    pnu                   VARCHAR(19),                                   -- 필지고유번호 — 공시가격 조회 키 (설계 I54)
    official_price        BIGINT,                                        -- 공시가격(원)
    official_price_year   INTEGER,                                       -- 공시가격 기준연도
    source_type           VARCHAR(20),                                   -- MANUAL | PASTE | CRAWL
    source_url            VARCHAR(1000),                                 -- 원본(네이버) URL — 생존 확인 배치 대상 (설계 I62)
    naver_article_no      VARCHAR(50),                                   -- 매물번호
    raw_paste_text        TEXT,                                          -- 원문 보존 → 재파싱용
    parser_version        VARCHAR(50),
    parse_confidence      JSONB,                                         -- 필드별 EXACT|DERIVED|MISSING
    is_draft              BOOLEAN      NOT NULL DEFAULT FALSE,
    listing_status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',        -- ACTIVE|SOLD_OUT|UNREACHABLE|ARCHIVED
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    last_checked_at       TIMESTAMPTZ,
    check_fail_streak     INTEGER      NOT NULL DEFAULT 0,
    sold_detected_at      TIMESTAMPTZ,
    created_by            BIGINT       REFERENCES users (id),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_property_listing_status ON property (listing_status, active);
CREATE INDEX ix_property_deal_type      ON property (deal_type);
CREATE INDEX ix_property_created_by     ON property (created_by);
CREATE INDEX ix_property_name           ON property (name);
CREATE INDEX ix_property_source_url     ON property (source_url) WHERE source_url IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 3. agent — 중개인
-- ---------------------------------------------------------------------------
CREATE TABLE agent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_name     VARCHAR(255),
    agent_name      VARCHAR(100),
    phone           VARCHAR(30),
    mobile          VARCHAR(30),
    registration_no VARCHAR(100),
    address         VARCHAR(500),
    lat             NUMERIC(12, 8),
    lng             NUMERIC(12, 8)
);

-- ---------------------------------------------------------------------------
-- 4. property_agent — 매물:중개인 N:M
-- ---------------------------------------------------------------------------
CREATE TABLE property_agent (
    property_id BIGINT  NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    agent_id    BIGINT  NOT NULL REFERENCES agent (id)    ON DELETE CASCADE,
    is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (property_id, agent_id)
);
CREATE INDEX ix_property_agent_agent ON property_agent (agent_id);

-- ---------------------------------------------------------------------------
-- 5. property_image — 매물 이미지 (도면/실사)
-- ---------------------------------------------------------------------------
CREATE TABLE property_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    image_type   VARCHAR(20) NOT NULL,                                   -- FLOOR_PLAN | PHOTO
    storage_path VARCHAR(500) NOT NULL,
    sort_order   INTEGER     NOT NULL DEFAULT 0
);
CREATE INDEX ix_property_image_property ON property_image (property_id, sort_order);

-- ---------------------------------------------------------------------------
-- 6. criterion — 평가 항목
-- ---------------------------------------------------------------------------
CREATE TABLE criterion (
    code         VARCHAR(50) PRIMARY KEY,                                -- COMFORT|PRICE|MOVE_IN|COMMUTE|AGE|FLOOR|STATION|EDUCATION|AMENITY|PARKING|GREEN|HOUSEHOLDS
    name         VARCHAR(100) NOT NULL,
    scoring_type VARCHAR(20)  NOT NULL,                                  -- AUTO | MANUAL | HYBRID
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------------
-- 7. criterion_weight — 평가 항목 가중치(우선순위)
-- ---------------------------------------------------------------------------
CREATE TABLE criterion_weight (
    criterion_code VARCHAR(50) PRIMARY KEY REFERENCES criterion (code),
    priority_rank  INTEGER     NOT NULL,                                 -- 1 = 최우선
    weight         NUMERIC(6, 2) NOT NULL,                               -- 가중치 배수
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_criterion_weight_rank ON criterion_weight (priority_rank);

-- ---------------------------------------------------------------------------
-- 8. property_score — 매물별 항목 점수
-- ---------------------------------------------------------------------------
CREATE TABLE property_score (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    criterion_code VARCHAR(50) NOT NULL REFERENCES criterion (code),
    auto_score     NUMERIC(6, 2),                                        -- 0~100
    manual_score   NUMERIC(6, 2),
    effective_score NUMERIC(6, 2),
    score_source   VARCHAR(20),                                          -- AUTO | MANUAL | FALLBACK
    fallback_reason VARCHAR(255),                                         -- 미산출 사유 (설계 I47)
    explanation    VARCHAR(500),                                          -- 자동 채점 산출 근거 (설계 I50)
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_property_score UNIQUE (property_id, criterion_code)
);
CREATE INDEX ix_property_score_criterion ON property_score (criterion_code);

-- ---------------------------------------------------------------------------
-- 9. user_criterion_score — 사용자별 수동 점수 (COMFORT 등)
-- ---------------------------------------------------------------------------
CREATE TABLE user_criterion_score (
    property_id    BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id        BIGINT      NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    criterion_code VARCHAR(50) NOT NULL REFERENCES criterion (code),
    score          INTEGER     NOT NULL,                                 -- 1~5 또는 0~100
    PRIMARY KEY (property_id, user_id, criterion_code)
);
CREATE INDEX ix_user_criterion_score_user ON user_criterion_score (user_id);

-- ---------------------------------------------------------------------------
-- 10. commute_result — 사용자별 직장 통근 결과
-- ---------------------------------------------------------------------------
CREATE TABLE commute_result (
    property_id    BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id        BIGINT      NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    total_minutes  INTEGER,
    transfer_count INTEGER,
    walk_minutes   INTEGER,
    path_summary   JSONB,
    fetched_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (property_id, user_id)
);

-- ---------------------------------------------------------------------------
-- 11. (삭제됨) nearby_facility — 매물 주변 POI
--     영속 데이터가 아니라 카카오 응답 캐시이므로 PoiCache(live=Redis / local=인메모리,
--     TTL 30일, 키에 수집 규칙 버전 포함)로 옮겼다. 설계 16-I44.
--     기존 DB에서는 아래로 정리한다:  DROP TABLE IF EXISTS nearby_facility;
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 12. property_opinion — 매물 Merit/Demerit 의견
-- ---------------------------------------------------------------------------
CREATE TABLE property_opinion (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id      BIGINT      NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    opinion_type VARCHAR(20) NOT NULL,                                   -- MERIT | DEMERIT
    content      VARCHAR(1000) NOT NULL,
    sort_order   INTEGER     NOT NULL DEFAULT 0
);
CREATE INDEX ix_property_opinion_property ON property_opinion (property_id, sort_order);

-- ---------------------------------------------------------------------------
-- 13. listing_check_log — 매물 생존 확인 로그
-- ---------------------------------------------------------------------------
CREATE TABLE listing_check_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    checked_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    http_status INTEGER,
    verdict     VARCHAR(20),                                             -- ALIVE | GONE | BLOCKED | ERROR
    evidence    VARCHAR(1000),                                           -- 판정 근거 스니펫
    elapsed_ms  INTEGER,
    notified    BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_listing_check_log_property ON listing_check_log (property_id, checked_at);

-- ---------------------------------------------------------------------------
-- 14. system_config — 시스템 설정 (Slack은 yaml로 이관됨)
-- ---------------------------------------------------------------------------
CREATE TABLE system_config (
    config_key   VARCHAR(100) PRIMARY KEY,
    config_value VARCHAR(1000),
    value_type   VARCHAR(20) NOT NULL DEFAULT 'STRING',                  -- STRING | INT | BOOL | SECRET
    category     VARCHAR(20),                                            -- BATCH | SCORING | LOAN
    description  VARCHAR(500),
    masked       BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_by   BIGINT      REFERENCES users (id),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_system_config_category ON system_config (category);

-- ---------------------------------------------------------------------------
-- 15. notification_log — 알림 발송 이력
-- ---------------------------------------------------------------------------
CREATE TABLE notification_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    VARCHAR(50) NOT NULL,                                  -- PROPERTY_CREATED|LISTING_SOLD_OUT|BATCH_*...
    property_id   BIGINT      REFERENCES property (id) ON DELETE SET NULL,
    channel       VARCHAR(20),
    status        VARCHAR(20) NOT NULL DEFAULT 'RETRYING',               -- SENT | FAILED | RETRYING
    retry_count   INTEGER     NOT NULL DEFAULT 0,
    error_message VARCHAR(1000),
    payload       JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at       TIMESTAMPTZ
);
CREATE INDEX ix_notification_log_status ON notification_log (status, created_at);

-- ---------------------------------------------------------------------------
-- 16. reference_transaction — 국토부 실거래가 (참고 표기 전용)
-- ---------------------------------------------------------------------------
CREATE TABLE reference_transaction (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id   BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    deal_type     VARCHAR(20),                                           -- TRADE | RENT
    contract_date DATE,
    price         BIGINT,
    area_m2       NUMERIC(10, 2),                                        -- 전용면적 — 단가 환산에 쓴다 (설계 I65)
    floor_no      INTEGER,
    source        VARCHAR(30),                                           -- MINISTRY_TRADE | MINISTRY_RENT
    cached_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_reference_transaction_property ON reference_transaction (property_id, contract_date);

-- ---------------------------------------------------------------------------
-- 17. loan_estimate — 대출 한도 시뮬레이션 결과
-- ---------------------------------------------------------------------------
CREATE TABLE loan_estimate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id     BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    product_type    VARCHAR(20),                                         -- MORTGAGE | JEONSE
    ltv_rate        NUMERIC(6, 4),
    ltv_limit       BIGINT,
    dsr_limit       BIGINT,
    final_limit     BIGINT,
    required_cash   BIGINT,
    acquisition_tax BIGINT,
    assumptions     JSONB,
    computed_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_loan_estimate_property ON loan_estimate (property_id, computed_at);

-- ---------------------------------------------------------------------------
-- 18. property_visit_plan — 임장 플래너 (계획)
-- ---------------------------------------------------------------------------
CREATE TABLE property_comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id     BIGINT        NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    content     VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    -- 사람당 매물 하나에 한 건 (설계 I56). 여러 생각은 한 글을 고쳐 쓴다
    CONSTRAINT uq_property_comment UNIQUE (property_id, user_id)
);
CREATE INDEX idx_property_comment_property ON property_comment (property_id);
CREATE TABLE llm_recommendation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    score        NUMERIC(6, 2),                                  -- 0~100 추천도
    reason       VARCHAR(2000),                                  -- 그 점수를 준 이유
    model        VARCHAR(100),                                   -- 무엇으로 매긴 점수인지 남긴다
    prompt_hash  VARCHAR(64),                                    -- 입력이 그대로면 다시 부르지 않는다
    workplace_count INTEGER    NOT NULL DEFAULT 0,                -- 추론에 쓰인 직장 위치 수 (설계 I60)
    computed_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_llm_recommendation UNIQUE (property_id)
);
CREATE TABLE comparative_analysis (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    rank_no        INTEGER,                                        -- 1위가 가장 좋은 매물
    score          NUMERIC(6, 2),                                  -- 0~100 비교 우위 점수
    reason         VARCHAR(2000),                                  -- 다른 매물 대비 어떤 점이 낫고 못한지
    model          VARCHAR(100),
    batch_hash     VARCHAR(64),                                    -- 분석에 쓰인 매물 집합의 해시
    property_count INTEGER,                                        -- 함께 비교한 매물 수
    computed_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_comparative_analysis UNIQUE (property_id)
);
CREATE TABLE property_visit_plan (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_date            DATE,
    created_by            BIGINT NOT NULL REFERENCES users (id),
    start_address         VARCHAR(500),
    start_lat             NUMERIC(12, 8),
    start_lng             NUMERIC(12, 8),
    travel_mode           VARCHAR(20),                                   -- TRANSIT | DRIVING
    window_start          TIME,
    window_end            TIME,
    stay_minutes_default  INTEGER NOT NULL DEFAULT 25,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',          -- DRAFT | CONFIRMED | COMPLETED
    computed_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_property_visit_plan_created ON property_visit_plan (created_by, visit_date);

-- ---------------------------------------------------------------------------
-- 19. visit_plan_stop — 임장 방문 정거장
-- ---------------------------------------------------------------------------
CREATE TABLE visit_plan_stop (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id                 BIGINT NOT NULL REFERENCES property_visit_plan (id) ON DELETE CASCADE,
    property_id             BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    stop_order              INTEGER NOT NULL,
    estimated_arrival       TIME,
    estimated_departure     TIME,
    travel_minutes_from_prev INTEGER,
    travel_mode_segment     VARCHAR(20),
    visited                 BOOLEAN NOT NULL DEFAULT FALSE,
    visited_at              TIMESTAMPTZ,
    CONSTRAINT uq_visit_plan_stop_order UNIQUE (plan_id, stop_order)
);
CREATE INDEX ix_visit_plan_stop_property ON visit_plan_stop (property_id);

-- ---------------------------------------------------------------------------
-- 20. regulation_param — 대출 규제 파라미터 (프로파일별)
-- ---------------------------------------------------------------------------
CREATE TABLE regulation_param (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile     VARCHAR(50)  NOT NULL,                                   -- 규제 파라미터 세트 (예: '2025-10-15')
    param_key   VARCHAR(50)  NOT NULL,                                   -- LTV_RATE|MAX_LOAN_AMOUNT|DSR_LIMIT|STRESS_RATE|ACQUISITION_TAX_BANDS|BROKER_FEE_RATE|FIRST_HOME_PREF_RATE|JEONSE_GUARANTEE_LIMIT
    param_value VARCHAR(1000) NOT NULL,                                  -- 값(숫자·JSON은 문자열로 저장)
    value_type  VARCHAR(20)  NOT NULL DEFAULT 'STRING',                  -- STRING | INT | DECIMAL | JSON
    description VARCHAR(500),
    updated_by  BIGINT       REFERENCES users (id),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_regulation_param UNIQUE (profile, param_key)
);
CREATE INDEX ix_regulation_param_profile ON regulation_param (profile);

-- ---------------------------------------------------------------------------
-- 21. legal_dong_code — 법정동코드 참조 테이블 (행정안전부 공개 데이터)
-- ---------------------------------------------------------------------------
CREATE TABLE land_use (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT       NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    zone_code    VARCHAR(20),                                     -- prposAreaDstrcCode (예: UQA123)
    zone_name    VARCHAR(200) NOT NULL,                           -- 지역·지구명
    conflict     VARCHAR(10)  NOT NULL,                           -- INCLUDED | OVERLAP | ADJACENT
    pnu          VARCHAR(19),
    fetched_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_land_use_property ON land_use (property_id);
CREATE TABLE regulated_area (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_prefix  VARCHAR(10) NOT NULL,                                   -- 법정동코드 앞자리 (5=시군구, 10=법정동)
    zone         VARCHAR(30) NOT NULL,                                   -- ADJUSTMENT_TARGET | SPECULATION_OVERHEATED
    area_name    VARCHAR(200),                                           -- 사람이 알아볼 이름 (예: 서울 강남구)
    designated_on DATE,                                                  -- 고시 지정일
    released_on  DATE,                                                   -- 해제일. NULL이면 현재 유효
    note         VARCHAR(500),                                           -- 고시 번호 등 근거
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_regulated_area UNIQUE (code_prefix, zone, designated_on)
);
CREATE INDEX idx_regulated_area_prefix ON regulated_area (code_prefix);
CREATE TABLE legal_dong_code (
    code        VARCHAR(10) PRIMARY KEY,                                 -- 10자리 법정동코드
    sido        VARCHAR(100),
    sigungu     VARCHAR(100),
    dong_name   VARCHAR(100),
    ri_name     VARCHAR(100),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_legal_dong_code_dong ON legal_dong_code (sigungu, dong_name);

-- =============================================================================
-- 마이그레이션 — 2026-08-28 배포분 (Session 16-I41·I43·I44·I49·I50·I51)
--
-- 위 CREATE 문은 신규 구축용이다. **이미 운영 중인 DB**는 아래를 순서대로 실행한다.
-- 모두 멱등(idempotent)하므로 다시 돌려도 안전하다. 트랜잭션으로 묶어 실행할 것.
-- =============================================================================
BEGIN;

-- ---------------------------------------------------------------------------
-- 1. users — 로그인 ID와 이메일 분리 (I51)
--    기존에는 email이 로그인 ID를 겸했다. login_id로 옮기고 email은 연락처로 남긴다.
-- ---------------------------------------------------------------------------
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_id VARCHAR(50);
UPDATE users SET login_id = email WHERE login_id IS NULL;
ALTER TABLE users ALTER COLUMN login_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_login_id ON users (login_id);

-- 이메일은 선택 항목이 된다. 이메일 형식이 아닌 값(로그인 ID로 쓰이던 값)은 비워
-- 다음 로그인 때 최초 설정 단계에서 다시 받는다 (I48).
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
UPDATE users SET email = NULL WHERE email IS NOT NULL AND position('@' IN email) = 0;

-- ---------------------------------------------------------------------------
-- 2. property_score — 자동 채점 산출 근거 (I50)
--    기존 행의 explanation은 NULL이며, 재채점하면 채워진다.
-- ---------------------------------------------------------------------------
ALTER TABLE property_score ADD COLUMN IF NOT EXISTS explanation VARCHAR(500);

-- ---------------------------------------------------------------------------
-- 3. 채점 항목 교체 — BUILDING_COUNT(단지 동수) → HOUSEHOLDS(세대수) (I49)
--    가중치 순위는 그대로 승계한다. 점수 값은 옛 산식 기준이므로 재채점이 필요하다.
-- ---------------------------------------------------------------------------
INSERT INTO criterion (code, name, scoring_type, enabled)
VALUES ('HOUSEHOLDS', '세대수', 'AUTO', TRUE)
ON CONFLICT (code) DO NOTHING;

UPDATE criterion_weight SET criterion_code = 'HOUSEHOLDS' WHERE criterion_code = 'BUILDING_COUNT';
UPDATE property_score   SET criterion_code = 'HOUSEHOLDS' WHERE criterion_code = 'BUILDING_COUNT';
DELETE FROM criterion WHERE code = 'BUILDING_COUNT';

-- ---------------------------------------------------------------------------
-- 4. system_config — 채점 상수 키 제거 (I41)
--    화면에는 보이지만 채점 코드가 읽지 않아 혼란을 줬다. 앱도 부팅 시 지우지만 함께 정리한다.
-- ---------------------------------------------------------------------------
DELETE FROM system_config WHERE config_key IN ('scoring.floorPeak', 'scoring.weightCurve');

-- ---------------------------------------------------------------------------
-- 5. legal_dong_code — 잘못된 부트스트랩 시드 제거 (I43)
--    8건 중 5건의 시군구 코드가 틀려(마포구를 강남구 11680 등) 엉뚱한 구의 실거래가를
--    가져왔다. 이제 카카오 주소검색 b_code로 조회·캐시하므로 시드가 필요 없다.
-- ---------------------------------------------------------------------------
DELETE FROM legal_dong_code WHERE code IN (
    '1111000000', '1111000100', '1168000000', '1168000100',
    '1156000000', '1141000000', '1123000000', '1168000200'
);

-- ---------------------------------------------------------------------------
-- 6. nearby_facility — 테이블 폐지 (I44)
--    영속 데이터가 아니라 카카오 응답 캐시라 PoiCache(Redis, TTL 30일)로 옮겼다.
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS nearby_facility;

-- 5) 중개사·세금·초등학교 항목 (설계 I53)
--    중개사 정보 자체는 기존 agent / property_agent 테이블을 그대로 쓴다.
--    매물마다 달라지는 값(보수·세금)과 입지 항목(초등학교)만 property에 붙인다.
ALTER TABLE property ADD COLUMN IF NOT EXISTS brokerage_fee       BIGINT;
ALTER TABLE property ADD COLUMN IF NOT EXISTS brokerage_rate      NUMERIC(4, 2);
ALTER TABLE property ADD COLUMN IF NOT EXISTS acquisition_tax     BIGINT;
ALTER TABLE property ADD COLUMN IF NOT EXISTS property_tax        BIGINT;
ALTER TABLE property ADD COLUMN IF NOT EXISTS comprehensive_tax   VARCHAR(100);
ALTER TABLE property ADD COLUMN IF NOT EXISTS school_name         VARCHAR(255);
ALTER TABLE property ADD COLUMN IF NOT EXISTS school_walk_minutes INTEGER;
ALTER TABLE property ADD COLUMN IF NOT EXISTS school_source       VARCHAR(20);

-- 6) 공시가격 (설계 I54 — V-World 공동주택/개별주택 공시가격)
ALTER TABLE property ADD COLUMN IF NOT EXISTS pnu                 VARCHAR(19);
ALTER TABLE property ADD COLUMN IF NOT EXISTS official_price      BIGINT;
ALTER TABLE property ADD COLUMN IF NOT EXISTS official_price_year INTEGER;

-- 10) 규제지역 (설계 I66) — 국토부 고시로 지정·해제된다. 공개 API가 없어 사람이 관리한다
CREATE TABLE IF NOT EXISTS regulated_area (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_prefix   VARCHAR(10) NOT NULL,
    zone          VARCHAR(30) NOT NULL,
    area_name     VARCHAR(200),
    designated_on DATE,
    released_on   DATE,
    note          VARCHAR(500),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_regulated_area UNIQUE (code_prefix, zone, designated_on)
);
CREATE INDEX IF NOT EXISTS idx_regulated_area_prefix ON regulated_area (code_prefix);

-- 11) 토지이용계획 (설계 I69) — 토지거래허가구역·정비구역 등을 매물에 붙인다
CREATE TABLE IF NOT EXISTS land_use (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT       NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    zone_code   VARCHAR(20),
    zone_name   VARCHAR(200) NOT NULL,
    conflict    VARCHAR(10)  NOT NULL,
    pnu         VARCHAR(19),
    fetched_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_land_use_property ON land_use (property_id);

-- 12) 실거래 전용면적 (설계 I65) — 단가(원/㎡) 환산으로 담보가치를 보정한다
ALTER TABLE reference_transaction ADD COLUMN IF NOT EXISTS area_m2 NUMERIC(10, 2);


-- 7) 연소득·기존 대출액 (설계 I55) — available_budget은 '보유 현금'으로 뜻이 확정됐다
ALTER TABLE users ADD COLUMN IF NOT EXISTS annual_income BIGINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS existing_loan BIGINT NOT NULL DEFAULT 0;

-- 8) 매물 코멘트 (설계 I56)
CREATE TABLE IF NOT EXISTS property_comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id     BIGINT        NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    content     VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    CONSTRAINT uq_property_comment UNIQUE (property_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_property_comment_property ON property_comment (property_id);

-- 9) LLM 추천도 (설계 I59)
CREATE TABLE IF NOT EXISTS comparative_analysis (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    rank_no        INTEGER,
    score          NUMERIC(6, 2),
    reason         VARCHAR(2000),
    model          VARCHAR(100),
    batch_hash     VARCHAR(64),
    property_count INTEGER,
    computed_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_comparative_analysis UNIQUE (property_id)
);

INSERT INTO criterion (code, name, scoring_type, enabled)
VALUES ('COMPARATIVE_ADVANTAGE', '비교 우위 추천', 'AUTO', TRUE)
ON CONFLICT (code) DO NOTHING;

CREATE TABLE IF NOT EXISTS llm_recommendation (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT        NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    score        NUMERIC(6, 2),
    reason       VARCHAR(2000),
    model        VARCHAR(100),
    prompt_hash  VARCHAR(64),
    workplace_count INTEGER    NOT NULL DEFAULT 0,
    computed_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_llm_recommendation UNIQUE (property_id)
);

-- LLM_RECOMMENDATION 채점 항목 추가 (가중치는 마지막 순위로)
INSERT INTO criterion (code, name, scoring_type, enabled)
VALUES ('LLM_RECOMMENDATION', 'AI 추천도', 'AUTO', TRUE)
ON CONFLICT (code) DO NOTHING;

COMMIT;

-- ---------------------------------------------------------------------------
-- 적용 후 할 일
--   1) 매물별 재채점: POST /api/properties/{id}/rescore
--      - HOUSEHOLDS는 옛 산식(동 수) 기준 점수가 남아 있고, explanation도 비어 있다
--      - POI는 PoiCache가 비어 있으므로 첫 재채점에서 카카오를 다시 호출한다
--   2) 계정 확인: 로그인 ID가 기존 이메일 값으로 채워졌다. 필요하면 사용자 관리에서 바꾼다
--   3) 이메일이 비워진 계정은 다음 로그인에서 최초 설정 모달이 뜬다 (I48)
-- ---------------------------------------------------------------------------

-- =============================================================================
-- 시드 데이터 참고 (DDL 아님 — 애플리케이션 부팅/적재 담당)
--   - criterion(12건)·criterion_weight: 부팅 시 yml 시드
--   - system_config: 부팅 시 yml 시드, 이후 DB 우선
--   - legal_dong_code: 행정안전부 공개 데이터 일괄 적재
--   - regulation_param: loan.regulation.profile 기준 기본 프로파일 시드
-- =============================================================================

-- ===== 13. 규제지역 고시 적재 상태 (설계 I73) =====
-- 규제지역 데이터가 없으면 비규제(LTV 0.7)로 계산되어 한도를 과대평가한다.
-- 그 사실을 화면에 실어 보내려면 적재가 끝났는지를 알아야 한다.

CREATE TABLE IF NOT EXISTS regulation_notice (
    zone          VARCHAR(30) PRIMARY KEY,
    notice_no     VARCHAR(50),
    announced_on  DATE,
    seed_status   VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
    area_count    INT NOT NULL DEFAULT 0,
    message       VARCHAR(500),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ===== 14. 회원 이메일 폐지 (설계 I74) =====
-- 이메일은 로그인에도 알림에도 쓰지 않아 받아 두기만 하던 항목이었다.
-- 표시 이름은 닉네임이 맡는다 — 매물 등록자 배지도 이미 닉네임을 쓴다.
DROP INDEX IF EXISTS ux_users_email;
ALTER TABLE users DROP COLUMN IF EXISTS email;

-- ===== 15. 그룹 (설계 I87) =====
-- 회원과 매물이 속하는 단위. 같은 그룹의 회원만 그 매물을 본다.
CREATE TABLE IF NOT EXISTS user_group (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users    ADD COLUMN IF NOT EXISTS group_id BIGINT;              -- admin은 NULL
ALTER TABLE property ADD COLUMN IF NOT EXISTS group_id BIGINT;              -- 아래 백필 후 NOT NULL

-- 닉네임 스냅샷 (설계 I88). 탈퇴하면 users 행이 사라져 조회로는 이름을 알 수 없다.
ALTER TABLE property         ADD COLUMN IF NOT EXISTS created_by_nickname VARCHAR(50);
ALTER TABLE property_comment ADD COLUMN IF NOT EXISTS author_nickname     VARCHAR(50);

-- 탈퇴해도 의견은 남아야 한다 (규칙 15). users를 CASCADE로 참조하던 것을 끊는다.
ALTER TABLE property_opinion DROP CONSTRAINT IF EXISTS property_opinion_user_id_fkey;

-- 기존 자료 편입: 이게 없으면 기동 즉시 아무도 자기 매물을 못 본다.
-- 애플리케이션이 GroupMigrationBootstrap으로 자동 수행하므로 수동 실행은 불필요하다.

-- ===== 16. 그룹 초대 코드 (설계 I89) =====
-- 코드가 기본키라 살아 있는 코드끼리 중복이 불가능하다(규칙 8).
-- 만료된 코드는 배치가 지우므로 같은 문자열이 나중에 다시 쓰일 수 있다.

CREATE TABLE IF NOT EXISTS group_invite (
    code       VARCHAR(8) PRIMARY KEY,
    group_id   BIGINT NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- ===== 17. 종류별 기존 부채 (설계 I92) =====
-- DSR 산정만기가 종류마다 달라 한 덩어리로 보면 한도가 실제보다 크게 나온다.
-- users.existing_loan은 폴백으로 남긴다 — 아직 종류를 입력하지 않은 사용자의
-- 부채가 통째로 사라지면 한도가 부풀려진다.

CREATE TABLE IF NOT EXISTS user_debt (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    debt_type  VARCHAR(30)  NOT NULL,
    amount     BIGINT       NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_debt UNIQUE (user_id, debt_type)
);

-- ===== 18. 월세 폐지 (설계 I94) =====
-- 이 앱은 집을 '사는' 결정을 돕는다. 월세는 담보도 자산도 아니라
-- LTV·DSR·취득세 계산이 통째로 의미가 없다.
--
-- ⚠️ 기존에 월세로 등록된 매물이 있으면 먼저 확인하고 지운다.
--    DealType에서 MONTHLY가 사라져 그대로 두면 조회 시 매핑이 실패한다.
-- SELECT id, name FROM property WHERE deal_type = 'MONTHLY';
-- DELETE FROM property WHERE deal_type = 'MONTHLY';

ALTER TABLE property DROP COLUMN IF EXISTS price_monthly;

-- ===== 19. 그룹별 Slack 웹훅 (설계 I96) =====
-- 알림도 그룹 경계를 지켜야 한다. 전역 웹훅 하나로 보내면 우리 매물이
-- 남의 채널에 뜬다. 매물 알림은 그 매물의 그룹 웹훅으로만 나간다.
ALTER TABLE user_group ADD COLUMN IF NOT EXISTS slack_webhook_url VARCHAR(500);

-- ===== 20. 프로필 확인 (설계 I100) =====
-- 관리자가 대신 넣은 정보를 본인이 한 번 확인해야 한다.
-- 값이 채워져 있는 것과 본인이 맞다고 한 것은 다르다.
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_confirmed BOOLEAN NOT NULL DEFAULT FALSE;

-- ---------------------------------------------------------------------------
-- 30. monthly_trade_cache — 법정동·월별 실거래 원본 캐시 (설계 I128)
--     같은 법정동·같은 달은 매물이 달라도 국토부 응답이 같다. 가격 전망이 60개월을
--     훑는데 매물마다 60번씩 부르면 등록이 몇 분씩 걸린다.
--     거래는 JSON 배열 하나로 담는다 — 통째로 읽고 통째로 쓰는 용도라 쪼갤 이유가 없다.
-- ---------------------------------------------------------------------------
CREATE TABLE monthly_trade_cache (
    lawd_cd     VARCHAR(5)  NOT NULL,                       -- 법정동코드 앞 5자리(시군구)
    deal_ym     VARCHAR(6)  NOT NULL,                       -- yyyyMM
    deal_type   VARCHAR(20) NOT NULL DEFAULT 'TRADE',       -- TRADE|JEONSE (설계 I131)
    payload     JSONB,                                      -- 국토부 응답을 그대로
    trade_count INT         NOT NULL DEFAULT 0,             -- 사람이 눈으로 볼 때 쓰는 값
    fetched_at  TIMESTAMP WITH TIME ZONE NOT NULL,          -- 과거 달은 안 바뀌므로 최근만 재조회
    PRIMARY KEY (lawd_cd, deal_ym, deal_type)
);
CREATE INDEX ix_monthly_trade_cache_fetched ON monthly_trade_cache (fetched_at);

-- ---------------------------------------------------------------------------
-- 31. price_forecast — 가격 전망 (설계 I135)
--     direction 은 결론(LLM), code_direction 은 규칙 기반 예측이다.
--     둘 다 저장해야 나중에 실제 결과와 맞춰 어느 쪽이 더 맞았는지 볼 수 있다.
-- ---------------------------------------------------------------------------
CREATE TABLE price_forecast (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT       NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    direction      VARCHAR(20)  NOT NULL,                  -- 결론 = LLM 예측
    code_direction VARCHAR(20),                            -- 코드 예측 (LLM에는 넘기지 않은 값)
    confidence     VARCHAR(20)  NOT NULL,
    horizon_months INT          NOT NULL,
    factors        JSONB,                                  -- 요인 배열 (근거 포함)
    caveats        JSONB,
    model          VARCHAR(100),                           -- LLM 없이 냈으면 NULL
    prompt_hash    VARCHAR(64),                            -- 같은 지표면 다시 묻지 않는다 (I59)
    computed_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX ux_price_forecast_property ON price_forecast (property_id);
