-- =============================================================================
-- Halley — 부동산 매물 비교·평가 웹앱 DB 스키마 (PostgreSQL)
--
-- 대상 : live = PostgreSQL, local = H2 (PostgreSQL 호환 모드)
--        JSONB 등 PostgreSQL 전용 기능은 outbound adapter 뒤에 격리한다 (설계서 2.3).
-- 명명 : snake_case, PK는 BIGINT IDENTITY (자연키 테이블 제외).
-- 근거 : docs/DESIGN.md 4장(ERD), 10.2(임장), 3.4/16-I35(규제 파라미터), 5.5(법정동코드)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. users — 사용자 (Admin이 생성, 회원가입 없음)
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname             VARCHAR(50)  NOT NULL,
    email                VARCHAR(255) NOT NULL,
    password_hash        VARCHAR(255) NOT NULL,
    role                 VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',        -- ADMIN | MEMBER
    workplace_name       VARCHAR(255),
    workplace_lat        NUMERIC(12, 8),
    workplace_lng        NUMERIC(12, 8),
    must_change_password BOOLEAN      NOT NULL DEFAULT TRUE,
    available_budget     BIGINT       NOT NULL DEFAULT 0,               -- 가용 예산(원) — 예산상한 합산용
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    disabled_at          TIMESTAMPTZ,
    disabled_by          BIGINT       REFERENCES users (id),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_users_nickname ON users (nickname);
CREATE UNIQUE INDEX ux_users_email    ON users (email);
CREATE INDEX        ix_users_role     ON users (role);

-- ---------------------------------------------------------------------------
-- 2. property — 매물
-- ---------------------------------------------------------------------------
CREATE TABLE property (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255),                                  -- 단지명
    dong_ho               VARCHAR(100),                                  -- 동/호
    deal_type             VARCHAR(20),                                   -- SALE | JEONSE | MONTHLY
    price_deposit         BIGINT,                                        -- 매매가 or 보증금(원)
    price_monthly         BIGINT,                                        -- 월세(원)
    maintenance_fee       INTEGER,
    address_road          VARCHAR(500),
    address_jibun         VARCHAR(500),
    lat                   NUMERIC(12, 8),
    lng                   NUMERIC(12, 8),
    area_supply_m2        NUMERIC(10, 2),                                -- 공급면적(㎡)
    area_exclusive_m2     NUMERIC(10, 2),                                -- 전용면적(㎡)
    floor_raw             VARCHAR(50),                                   -- '7' or '고/중/저'
    floor_no              INTEGER,
    floor_total           INTEGER,
    floor_band            VARCHAR(10),                                   -- HIGH | MID | LOW
    room_bath             VARCHAR(20),                                   -- '3/2'
    direction             VARCHAR(50),
    approval_year         INTEGER,                                       -- 사용승인연도
    move_in_type          VARCHAR(20),                                   -- IMMEDIATE | NEGOTIABLE | DATE
    move_in_date          DATE,
    parking_per_household NUMERIC(5, 2),                                 -- 세대당 주차대수
    total_households      INTEGER,
    heating_type          VARCHAR(50),
    building_count        INTEGER,                                       -- 단지 동수 — 수기 입력
    kb_price              BIGINT,                                        -- KB시세 — 대출 산정 기준
    source_type           VARCHAR(20),                                   -- MANUAL | PASTE | CRAWL
    source_url            VARCHAR(1000),
    naver_article_no      VARCHAR(50),                                   -- 매물번호
    raw_paste_text        TEXT,                                          -- 원문 보존 → 재파싱용
    parser_version        VARCHAR(50),
    parse_confidence      JSONB,                                         -- 필드별 EXACT|DERIVED|MISSING
    is_draft              BOOLEAN      NOT NULL DEFAULT FALSE,
    listing_status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',        -- ACTIVE|SOLD_OUT|UNREACHABLE|ARCHIVED
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    last_checked_at       TIMESTAMPTZ,
    check_fail_streak     INTEGER      NOT NULL DEFAULT 0,
    sold_detected_at      TIMESTAMPTZ,
    created_by            BIGINT       REFERENCES users (id),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX ix_property_listing_status ON property (listing_status, active);
CREATE INDEX ix_property_deal_type      ON property (deal_type);
CREATE INDEX ix_property_created_by     ON property (created_by);
CREATE INDEX ix_property_name           ON property (name);
CREATE INDEX ix_property_source_url     ON property (source_url) WHERE source_url IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 3. agent — 중개인
-- ---------------------------------------------------------------------------
CREATE TABLE agent (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    office_name     VARCHAR(255),
    agent_name      VARCHAR(100),
    phone           VARCHAR(30),
    mobile          VARCHAR(30),
    registration_no VARCHAR(100),
    address         VARCHAR(500),
    lat             NUMERIC(12, 8),
    lng             NUMERIC(12, 8)
);

-- ---------------------------------------------------------------------------
-- 4. property_agent — 매물:중개인 N:M
-- ---------------------------------------------------------------------------
CREATE TABLE property_agent (
    property_id BIGINT  NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    agent_id    BIGINT  NOT NULL REFERENCES agent (id)    ON DELETE CASCADE,
    is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (property_id, agent_id)
);
CREATE INDEX ix_property_agent_agent ON property_agent (agent_id);

-- ---------------------------------------------------------------------------
-- 5. property_image — 매물 이미지 (도면/실사)
-- ---------------------------------------------------------------------------
CREATE TABLE property_image (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    image_type   VARCHAR(20) NOT NULL,                                   -- FLOOR_PLAN | PHOTO
    storage_path VARCHAR(500) NOT NULL,
    sort_order   INTEGER     NOT NULL DEFAULT 0
);
CREATE INDEX ix_property_image_property ON property_image (property_id, sort_order);

-- ---------------------------------------------------------------------------
-- 6. criterion — 평가 항목
-- ---------------------------------------------------------------------------
CREATE TABLE criterion (
    code         VARCHAR(50) PRIMARY KEY,                                -- COMFORT|PRICE|MOVE_IN|COMMUTE|AGE|FLOOR|STATION|EDUCATION|AMENITY|PARKING|GREEN|HOUSEHOLDS
    name         VARCHAR(100) NOT NULL,
    scoring_type VARCHAR(20)  NOT NULL,                                  -- AUTO | MANUAL | HYBRID
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------------
-- 7. criterion_weight — 평가 항목 가중치(우선순위)
-- ---------------------------------------------------------------------------
CREATE TABLE criterion_weight (
    criterion_code VARCHAR(50) PRIMARY KEY REFERENCES criterion (code),
    priority_rank  INTEGER     NOT NULL,                                 -- 1 = 최우선
    weight         NUMERIC(6, 2) NOT NULL,                               -- 가중치 배수
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_criterion_weight_rank ON criterion_weight (priority_rank);

-- ---------------------------------------------------------------------------
-- 8. property_score — 매물별 항목 점수
-- ---------------------------------------------------------------------------
CREATE TABLE property_score (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id    BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    criterion_code VARCHAR(50) NOT NULL REFERENCES criterion (code),
    auto_score     NUMERIC(6, 2),                                        -- 0~100
    manual_score   NUMERIC(6, 2),
    effective_score NUMERIC(6, 2),
    score_source   VARCHAR(20),                                          -- AUTO | MANUAL | FALLBACK
    fallback_reason VARCHAR(255),                                         -- 미산출 사유 (설계 I47)
    explanation    VARCHAR(500),                                          -- 자동 채점 산출 근거 (설계 I50)
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_property_score UNIQUE (property_id, criterion_code)
);
CREATE INDEX ix_property_score_criterion ON property_score (criterion_code);

-- ---------------------------------------------------------------------------
-- 9. user_criterion_score — 사용자별 수동 점수 (COMFORT 등)
-- ---------------------------------------------------------------------------
CREATE TABLE user_criterion_score (
    property_id    BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id        BIGINT      NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    criterion_code VARCHAR(50) NOT NULL REFERENCES criterion (code),
    score          INTEGER     NOT NULL,                                 -- 1~5 또는 0~100
    PRIMARY KEY (property_id, user_id, criterion_code)
);
CREATE INDEX ix_user_criterion_score_user ON user_criterion_score (user_id);

-- ---------------------------------------------------------------------------
-- 10. commute_result — 사용자별 직장 통근 결과
-- ---------------------------------------------------------------------------
CREATE TABLE commute_result (
    property_id    BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id        BIGINT      NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    total_minutes  INTEGER,
    transfer_count INTEGER,
    walk_minutes   INTEGER,
    path_summary   JSONB,
    fetched_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (property_id, user_id)
);

-- ---------------------------------------------------------------------------
-- 11. (삭제됨) nearby_facility — 매물 주변 POI
--     영속 데이터가 아니라 카카오 응답 캐시이므로 PoiCache(live=Redis / local=인메모리,
--     TTL 30일, 키에 수집 규칙 버전 포함)로 옮겼다. 설계 16-I44.
--     기존 DB에서는 아래로 정리한다:  DROP TABLE IF EXISTS nearby_facility;
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 12. property_opinion — 매물 Merit/Demerit 의견
-- ---------------------------------------------------------------------------
CREATE TABLE property_opinion (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id  BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    user_id      BIGINT      NOT NULL REFERENCES users (id)    ON DELETE CASCADE,
    opinion_type VARCHAR(20) NOT NULL,                                   -- MERIT | DEMERIT
    content      VARCHAR(1000) NOT NULL,
    sort_order   INTEGER     NOT NULL DEFAULT 0
);
CREATE INDEX ix_property_opinion_property ON property_opinion (property_id, sort_order);

-- ---------------------------------------------------------------------------
-- 13. listing_check_log — 매물 생존 확인 로그
-- ---------------------------------------------------------------------------
CREATE TABLE listing_check_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id BIGINT      NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    checked_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    http_status INTEGER,
    verdict     VARCHAR(20),                                             -- ALIVE | GONE | BLOCKED | ERROR
    evidence    VARCHAR(1000),                                           -- 판정 근거 스니펫
    elapsed_ms  INTEGER,
    notified    BOOLEAN     NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_listing_check_log_property ON listing_check_log (property_id, checked_at);

-- ---------------------------------------------------------------------------
-- 14. system_config — 시스템 설정 (Slack은 yaml로 이관됨)
-- ---------------------------------------------------------------------------
CREATE TABLE system_config (
    config_key   VARCHAR(100) PRIMARY KEY,
    config_value VARCHAR(1000),
    value_type   VARCHAR(20) NOT NULL DEFAULT 'STRING',                  -- STRING | INT | BOOL | SECRET
    category     VARCHAR(20),                                            -- BATCH | SCORING | LOAN
    description  VARCHAR(500),
    masked       BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_by   BIGINT      REFERENCES users (id),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_system_config_category ON system_config (category);

-- ---------------------------------------------------------------------------
-- 15. notification_log — 알림 발송 이력
-- ---------------------------------------------------------------------------
CREATE TABLE notification_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type    VARCHAR(50) NOT NULL,                                  -- PROPERTY_CREATED|LISTING_SOLD_OUT|BATCH_*...
    property_id   BIGINT      REFERENCES property (id) ON DELETE SET NULL,
    channel       VARCHAR(20),
    status        VARCHAR(20) NOT NULL DEFAULT 'RETRYING',               -- SENT | FAILED | RETRYING
    retry_count   INTEGER     NOT NULL DEFAULT 0,
    error_message VARCHAR(1000),
    payload       JSONB,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at       TIMESTAMPTZ
);
CREATE INDEX ix_notification_log_status ON notification_log (status, created_at);

-- ---------------------------------------------------------------------------
-- 16. reference_transaction — 국토부 실거래가 (참고 표기 전용)
-- ---------------------------------------------------------------------------
CREATE TABLE reference_transaction (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id   BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    deal_type     VARCHAR(20),                                           -- TRADE | RENT
    contract_date DATE,
    price         BIGINT,
    floor_no      INTEGER,
    source        VARCHAR(30),                                           -- MINISTRY_TRADE | MINISTRY_RENT
    cached_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_reference_transaction_property ON reference_transaction (property_id, contract_date);

-- ---------------------------------------------------------------------------
-- 17. loan_estimate — 대출 한도 시뮬레이션 결과
-- ---------------------------------------------------------------------------
CREATE TABLE loan_estimate (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id     BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    product_type    VARCHAR(20),                                         -- MORTGAGE | JEONSE
    ltv_rate        NUMERIC(6, 4),
    ltv_limit       BIGINT,
    dsr_limit       BIGINT,
    final_limit     BIGINT,
    required_cash   BIGINT,
    acquisition_tax BIGINT,
    assumptions     JSONB,
    computed_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_loan_estimate_property ON loan_estimate (property_id, computed_at);

-- ---------------------------------------------------------------------------
-- 18. property_visit_plan — 임장 플래너 (계획)
-- ---------------------------------------------------------------------------
CREATE TABLE property_visit_plan (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_date            DATE,
    created_by            BIGINT NOT NULL REFERENCES users (id),
    start_address         VARCHAR(500),
    start_lat             NUMERIC(12, 8),
    start_lng             NUMERIC(12, 8),
    travel_mode           VARCHAR(20),                                   -- TRANSIT | DRIVING
    window_start          TIME,
    window_end            TIME,
    stay_minutes_default  INTEGER NOT NULL DEFAULT 25,
    status                VARCHAR(20) NOT NULL DEFAULT 'DRAFT',          -- DRAFT | CONFIRMED | COMPLETED
    computed_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_property_visit_plan_created ON property_visit_plan (created_by, visit_date);

-- ---------------------------------------------------------------------------
-- 19. visit_plan_stop — 임장 방문 정거장
-- ---------------------------------------------------------------------------
CREATE TABLE visit_plan_stop (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id                 BIGINT NOT NULL REFERENCES property_visit_plan (id) ON DELETE CASCADE,
    property_id             BIGINT NOT NULL REFERENCES property (id) ON DELETE CASCADE,
    stop_order              INTEGER NOT NULL,
    estimated_arrival       TIME,
    estimated_departure     TIME,
    travel_minutes_from_prev INTEGER,
    travel_mode_segment     VARCHAR(20),
    visited                 BOOLEAN NOT NULL DEFAULT FALSE,
    visited_at              TIMESTAMPTZ,
    CONSTRAINT uq_visit_plan_stop_order UNIQUE (plan_id, stop_order)
);
CREATE INDEX ix_visit_plan_stop_property ON visit_plan_stop (property_id);

-- ---------------------------------------------------------------------------
-- 20. regulation_param — 대출 규제 파라미터 (프로파일별)
-- ---------------------------------------------------------------------------
CREATE TABLE regulation_param (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile     VARCHAR(50)  NOT NULL,                                   -- 규제 파라미터 세트 (예: '2025-10-15')
    param_key   VARCHAR(50)  NOT NULL,                                   -- LTV_RATE|MAX_LOAN_AMOUNT|DSR_LIMIT|STRESS_RATE|ACQUISITION_TAX_BANDS|BROKER_FEE_RATE|FIRST_HOME_PREF_RATE|JEONSE_GUARANTEE_LIMIT
    param_value VARCHAR(1000) NOT NULL,                                  -- 값(숫자·JSON은 문자열로 저장)
    value_type  VARCHAR(20)  NOT NULL DEFAULT 'STRING',                  -- STRING | INT | DECIMAL | JSON
    description VARCHAR(500),
    updated_by  BIGINT       REFERENCES users (id),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_regulation_param UNIQUE (profile, param_key)
);
CREATE INDEX ix_regulation_param_profile ON regulation_param (profile);

-- ---------------------------------------------------------------------------
-- 21. legal_dong_code — 법정동코드 참조 테이블 (행정안전부 공개 데이터)
-- ---------------------------------------------------------------------------
CREATE TABLE legal_dong_code (
    code        VARCHAR(10) PRIMARY KEY,                                 -- 10자리 법정동코드
    sido        VARCHAR(100),
    sigungu     VARCHAR(100),
    dong_name   VARCHAR(100),
    ri_name     VARCHAR(100),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_legal_dong_code_dong ON legal_dong_code (sigungu, dong_name);

-- =============================================================================
-- 시드 데이터 참고 (DDL 아님 — 애플리케이션 부팅/적재 담당)
--   - criterion(12건)·criterion_weight: 부팅 시 yml 시드
--   - system_config: 부팅 시 yml 시드, 이후 DB 우선
--   - legal_dong_code: 행정안전부 공개 데이터 일괄 적재
--   - regulation_param: loan.regulation.profile 기준 기본 프로파일 시드
-- =============================================================================
